# Generated by Django 5.0.6 on 2024-07-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_2app', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
